#!/usr/bin/env bash
#
# Provision an Azure VM ready to host coturn for FileTransferNow.
#
# What this does:
#   1. Creates a resource group
#   2. Spins up a Standard_B1s Ubuntu 24.04 VM with a static public IP
#   3. Opens all the TCP+UDP ports coturn needs (3478, 5349, 49152-65535, 80)
#   4. Prints the IP + next-steps DNS instructions
#
# What this does NOT do:
#   - Install coturn (that's 02-install-coturn.sh, run on the VM itself)
#   - Touch DNS (you do that manually after this script prints the IP)
#   - Configure your Cloudflare Worker (that's 04-wire-worker.sh)
#
# Prereqs:
#   - az CLI installed and logged in (`az login`)
#   - You've picked the right subscription (`az account set --subscription ...`)
#
# Idempotent: safe to re-run. If the RG already exists with a VM in it, this
# script will detect that and just re-print the IP + next steps instead of
# creating duplicates.
#
# Usage:
#   ./01-provision-vm.sh                              # uses defaults
#   RG=ftn-turn LOCATION=centralindia VM_SIZE=Standard_B1s ./01-provision-vm.sh
#

set -euo pipefail

# -------- Config (override via env vars) --------
RG="${RG:-ftn-turn}"
LOCATION="${LOCATION:-centralindia}"
VM_NAME="${VM_NAME:-ftn-turn-vm}"
VM_SIZE="${VM_SIZE:-Standard_B1s}"
ADMIN_USER="${ADMIN_USER:-azureuser}"

# Colors for the human reading output
G='\033[0;32m'; Y='\033[1;33m'; R='\033[0;31m'; B='\033[1;34m'; N='\033[0m'

step() { echo -e "\n${B}==>${N} $*"; }
ok() { echo -e "${G}✓${N} $*"; }
warn() { echo -e "${Y}⚠${N} $*"; }
err() { echo -e "${R}✗${N} $*"; }

# -------- Pre-flight checks --------
step "Pre-flight checks"

if ! command -v az &>/dev/null; then
  err "az CLI not found. Install: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash"
  exit 1
fi
ok "az CLI found"

if ! az account show &>/dev/null; then
  err "Not logged in to Azure. Run: az login"
  exit 1
fi
SUB=$(az account show --query name -o tsv)
ok "Logged in. Active subscription: ${B}${SUB}${N}"

# Confirm subscription is correct
read -rp "$(echo -e ${Y}Proceed with subscription \'${SUB}\'? [y/N]${N} )" CONFIRM
[[ "$CONFIRM" =~ ^[Yy]$ ]] || { warn "Aborted. Run 'az account set --subscription <name>' and re-run."; exit 1; }

# -------- Resource group --------
step "Creating resource group ${RG} in ${LOCATION}"
if az group show -n "$RG" &>/dev/null; then
  warn "Resource group ${RG} already exists — reusing."
else
  az group create -n "$RG" -l "$LOCATION" -o none
  ok "Created RG ${RG}"
fi

# -------- VM --------
step "Provisioning VM ${VM_NAME} (${VM_SIZE})"
if az vm show -g "$RG" -n "$VM_NAME" &>/dev/null; then
  warn "VM ${VM_NAME} already exists — reusing."
else
  az vm create \
    --resource-group "$RG" \
    --name "$VM_NAME" \
    --image Ubuntu2404 \
    --size "$VM_SIZE" \
    --admin-username "$ADMIN_USER" \
    --generate-ssh-keys \
    --public-ip-sku Standard \
    --public-ip-address-allocation Static \
    --location "$LOCATION" \
    --output none
  ok "VM created"
fi

TURN_IP=$(az vm show -d -g "$RG" -n "$VM_NAME" --query publicIps -o tsv)
ok "Public IP: ${B}${TURN_IP}${N}"

# -------- NSG rules --------
step "Opening firewall ports (TURN needs a lot)"

NIC_ID=$(az vm show -g "$RG" -n "$VM_NAME" --query 'networkProfile.networkInterfaces[0].id' -o tsv)
NSG_ID=$(az network nic show --ids "$NIC_ID" --query 'networkSecurityGroup.id' -o tsv)
NSG_NAME=$(basename "$NSG_ID")
ok "NSG: ${NSG_NAME}"

# Helper: create rule if not exists
ensure_rule() {
  local name="$1" priority="$2" protocol="$3" ports="$4"
  if az network nsg rule show -g "$RG" --nsg-name "$NSG_NAME" -n "$name" &>/dev/null; then
    warn "  rule ${name} exists — skipping"
    return
  fi
  az network nsg rule create -g "$RG" --nsg-name "$NSG_NAME" \
    --name "$name" --priority "$priority" \
    --protocol "$protocol" --destination-port-ranges $ports \
    --access Allow --direction Inbound --source-address-prefixes '*' \
    --output none
  ok "  + ${name} (${protocol}/${ports})"
}

ensure_rule AllowStunTurnTCP    1000 Tcp 3478
ensure_rule AllowTurnsTCP       1010 Tcp 5349
ensure_rule AllowRelayTCP       1020 Tcp 49152-65535
ensure_rule AllowHttpForCertbot 1030 Tcp 80
ensure_rule AllowStunTurnUDP    1040 Udp 3478
ensure_rule AllowTurnsUDP       1050 Udp 5349
ensure_rule AllowRelayUDP       1060 Udp 49152-65535

# -------- Save context for later scripts --------
CONTEXT_FILE="$(dirname "$0")/.turn-context"
cat > "$CONTEXT_FILE" <<EOF
# Generated by 01-provision-vm.sh — sourced by later scripts.
# Do NOT commit this file. (It's in .gitignore.)
RG=$RG
LOCATION=$LOCATION
VM_NAME=$VM_NAME
ADMIN_USER=$ADMIN_USER
TURN_IP=$TURN_IP
EOF
ok "Saved context to ${CONTEXT_FILE}"

# -------- Next steps --------
cat <<EOF

${G}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}
${G}✓ VM provisioned successfully${N}
${G}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}

  Public IP:     ${B}${TURN_IP}${N}
  Login:         ${B}ssh ${ADMIN_USER}@${TURN_IP}${N}

${Y}━━ NEXT STEP — DNS ━━${N}

  Add this DNS record in your domain registrar / Cloudflare DNS:

    ${B}Type${N}   A
    ${B}Name${N}   turn
    ${B}Value${N}  ${TURN_IP}
    ${B}TTL${N}    300  (5 min)

  Verify with:

    ${B}dig +short turn.filetransfernow.com @1.1.1.1${N}

  (Or: ${B}getent hosts turn.filetransfernow.com${N})

  Wait until the IP matches before running ${B}02-install-coturn.sh${N}.

${Y}━━ THEN ━━${N}

  Once DNS resolves correctly, copy the next script to the VM and run it:

    ${B}scp ./02-install-coturn.sh ${ADMIN_USER}@${TURN_IP}:~/${N}
    ${B}ssh ${ADMIN_USER}@${TURN_IP} 'TURN_DOMAIN=turn.filetransfernow.com LE_EMAIL=you@filetransfernow.com bash ~/02-install-coturn.sh'${N}

  The script prints a TURN_SHARED_SECRET at the end — save it; you'll need it
  in step 04 to wire up the Cloudflare Worker.

EOF
