#!/usr/bin/env bash
#
# Install + configure coturn on the Azure VM.
#
# RUN THIS *ON THE VM*, not on your laptop:
#   scp ./02-install-coturn.sh azureuser@<TURN_IP>:~/
#   ssh azureuser@<TURN_IP>
#   TURN_DOMAIN=turn.filetransfernow.com \
#   LE_EMAIL=you@filetransfernow.com \
#   bash ~/02-install-coturn.sh
#
# What this does:
#   1. apt-get update + install coturn, certbot
#   2. Fetches a Let's Encrypt TLS cert for $TURN_DOMAIN
#   3. Generates a 64-char shared secret for HMAC REST auth
#   4. Writes /etc/turnserver.conf with hardened defaults
#   5. Enables + starts the coturn systemd service
#   6. Installs a daily cert-renew cron job
#   7. Prints the TURN_SHARED_SECRET to copy into your Cloudflare Worker
#
# Idempotent: re-running re-checks each step and skips what's already done.
# The exception is the shared secret — if turnserver.conf already exists with
# a secret, we reuse it; we don't generate a new one (that would break clients).
#

set -euo pipefail

# -------- Config (override via env) --------
TURN_DOMAIN="${TURN_DOMAIN:?Set TURN_DOMAIN, e.g. TURN_DOMAIN=turn.filetransfernow.com}"
LE_EMAIL="${LE_EMAIL:?Set LE_EMAIL for Let's Encrypt notifications, e.g. LE_EMAIL=you@example.com}"

# Colors
G='\033[0;32m'; Y='\033[1;33m'; R='\033[0;31m'; B='\033[1;34m'; N='\033[0m'
step() { echo -e "\n${B}==>${N} $*"; }
ok() { echo -e "${G}✓${N} $*"; }
warn() { echo -e "${Y}⚠${N} $*"; }
err() { echo -e "${R}✗${N} $*"; }

# -------- Pre-flight --------
step "Pre-flight"
if [[ "$EUID" -ne 0 ]] && ! sudo -n true 2>/dev/null; then
  err "Need passwordless sudo or run as root."
  exit 1
fi

# Verify DNS resolves before we waste time trying to get a cert
step "Checking DNS for ${TURN_DOMAIN}"
RESOLVED_IP=$(getent hosts "$TURN_DOMAIN" | awk '{print $1}' | head -1 || true)
MY_PUB_IP=$(curl -s -4 ifconfig.me || curl -s -4 icanhazip.com || true)

if [[ -z "$RESOLVED_IP" ]]; then
  err "${TURN_DOMAIN} doesn't resolve. Add the DNS A record first."
  exit 1
fi
if [[ -n "$MY_PUB_IP" && "$RESOLVED_IP" != "$MY_PUB_IP" ]]; then
  warn "DNS points ${TURN_DOMAIN} → ${RESOLVED_IP}, but this VM is ${MY_PUB_IP}"
  warn "Either DNS hasn't propagated yet, or you're on the wrong VM."
  read -rp "$(echo -e ${Y}Continue anyway? [y/N]${N} )" CONFIRM
  [[ "$CONFIRM" =~ ^[Yy]$ ]] || exit 1
fi
ok "DNS: ${TURN_DOMAIN} → ${RESOLVED_IP}"

# -------- Install packages --------
step "Installing coturn + certbot"
sudo DEBIAN_FRONTEND=noninteractive apt-get update -qq
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq coturn certbot >/dev/null
ok "Packages installed"

# -------- TLS cert via Let's Encrypt --------
step "Fetching TLS cert for ${TURN_DOMAIN}"
CERT_DIR="/etc/letsencrypt/live/${TURN_DOMAIN}"
if [[ -f "${CERT_DIR}/fullchain.pem" ]]; then
  warn "Cert already exists at ${CERT_DIR} — skipping certbot."
else
  # Standalone mode binds port 80 — make sure nothing else is using it
  sudo systemctl stop coturn 2>/dev/null || true
  sudo certbot certonly --standalone \
    -d "$TURN_DOMAIN" \
    --non-interactive --agree-tos -m "$LE_EMAIL" \
    --no-eff-email
  ok "Cert obtained"
fi

# Coturn runs as user `turnserver`; needs read access on cert dir
sudo chgrp -R turnserver /etc/letsencrypt/live /etc/letsencrypt/archive
sudo chmod -R g+rx /etc/letsencrypt/live /etc/letsencrypt/archive
ok "Cert permissions set"

# -------- Shared secret --------
step "Generating / reusing TURN_SHARED_SECRET"
CONFIG_FILE=/etc/turnserver.conf
if [[ -f "$CONFIG_FILE" ]] && grep -q '^static-auth-secret=' "$CONFIG_FILE"; then
  TURN_SECRET=$(sudo grep '^static-auth-secret=' "$CONFIG_FILE" | cut -d= -f2-)
  warn "Reusing existing secret from ${CONFIG_FILE} (don't break live clients)"
else
  TURN_SECRET=$(openssl rand -hex 32)
  ok "Generated new 64-char secret"
fi

# -------- Find this VM's public IP (for relay-ip directive) --------
RELAY_IP="${MY_PUB_IP:-$RESOLVED_IP}"
ok "Will relay from IP: ${RELAY_IP}"

# -------- Write coturn config --------
step "Writing /etc/turnserver.conf"
sudo tee "$CONFIG_FILE" > /dev/null <<EOF
# Generated by 02-install-coturn.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Listening
listening-port=3478
tls-listening-port=5349
listening-ip=0.0.0.0
relay-ip=${RELAY_IP}
external-ip=${RELAY_IP}

# Realm — must match the URL clients connect to
realm=${TURN_DOMAIN}
server-name=${TURN_DOMAIN}

# REST API HMAC auth — your Cloudflare Worker mints time-limited creds
# using this same secret. Coturn validates them server-side without needing
# any connection back to the worker.
use-auth-secret
static-auth-secret=${TURN_SECRET}
lt-cred-mech

# TLS
cert=${CERT_DIR}/fullchain.pem
pkey=${CERT_DIR}/privkey.pem

# Relay port range — coturn uses these to forward media. MUST match the
# Azure NSG inbound rule (49152-65535/UDP+TCP).
min-port=49152
max-port=65535

# --- Hardening ---
no-cli
no-tlsv1
no-tlsv1_1
fingerprint

# Block relaying TO private / loopback / link-local addresses. Prevents
# someone from using your TURN server as a pivot into internal networks.
no-multicast-peers
denied-peer-ip=0.0.0.0-0.255.255.255
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=127.0.0.0-127.255.255.255
denied-peer-ip=169.254.0.0-169.254.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=224.0.0.0-239.255.255.255
denied-peer-ip=240.0.0.0-255.255.255.255

# --- Quotas (anti-abuse) ---
# Total simultaneous allocations across the whole server
total-quota=200
# Per-user (per-credential) allocation cap
user-quota=12
# Per-session bandwidth cap (2 Mbps is fine for any file transfer scenario)
max-bps=2000000

# --- Logging ---
log-file=/var/log/turnserver/turnserver.log
simple-log
EOF
ok "Config written"

# Log dir
sudo mkdir -p /var/log/turnserver
sudo chown turnserver:turnserver /var/log/turnserver

# Coturn is disabled by default on Ubuntu — flip the kill switch
sudo sed -i 's/^#*TURNSERVER_ENABLED=.*/TURNSERVER_ENABLED=1/' /etc/default/coturn

# -------- Start service --------
step "Starting coturn"
sudo systemctl enable coturn >/dev/null
sudo systemctl restart coturn

# Wait a beat, then check status
sleep 2
if sudo systemctl is-active --quiet coturn; then
  ok "coturn is running"
else
  err "coturn failed to start. Logs:"
  sudo journalctl -u coturn --no-pager -n 30
  exit 1
fi

# -------- Cert auto-renewal --------
step "Installing cert auto-renewal cron"
sudo tee /etc/cron.d/certbot-renew > /dev/null <<EOF
# Renew Let's Encrypt cert daily; restart coturn if renewed.
0 3 * * * root certbot renew --quiet --deploy-hook "systemctl restart coturn"
EOF
ok "Cron installed"

# Dry-run the renewal once to catch config errors early
sudo certbot renew --dry-run 2>&1 | tail -3

# -------- Print test credentials --------
step "Generating a test credential (10-min TTL)"
EXPIRY=$(($(date +%s) + 600))
TEST_USERNAME="${EXPIRY}:test"
TEST_CREDENTIAL=$(echo -n "$TEST_USERNAME" | openssl dgst -sha1 -hmac "$TURN_SECRET" -binary | base64)

# -------- Done --------
cat <<EOF

${G}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}
${G}✓ coturn deployed and running${N}
${G}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}

${Y}━━ COPY THIS SECRET ━━${N}

  ${B}TURN_SHARED_SECRET${N}=${TURN_SECRET}

  ${R}SAVE IT NOW.${N} You'll paste it into your Cloudflare Worker in step 04.
  Stash it in a password manager — it won't be displayed again unless you
  re-read /etc/turnserver.conf on this VM.

${Y}━━ TEST FROM YOUR LAPTOP ━━${N}

  Open https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
  Click "Remove server", then add:

    URI:        turn:${TURN_DOMAIN}:3478
    Username:   ${TEST_USERNAME}
    Credential: ${TEST_CREDENTIAL}

  Click "Add Server" → "Gather candidates".

  ${G}✓ SUCCESS${N} = at least one row with Type=${B}relay${N} appears
  ${R}✗ FAILURE${N} = only host/srflx, no relay → check logs: ${B}sudo tail -50 /var/log/turnserver/turnserver.log${N}

  (This test credential expires in 10 minutes; for fresh ones use 03-test.sh)

${Y}━━ NEXT STEP ━━${N}

  Back on your laptop:

    ${B}cd ~/projects/p2pdatesharing/scripts/turn-azure${N}
    ${B}TURN_DOMAIN=${TURN_DOMAIN} TURN_SHARED_SECRET='${TURN_SECRET}' ./04-wire-worker.sh${N}

EOF
